<?php

namespace Centrobill\Sdk\ValueObject;

use Centrobill\Sdk\Exception\CountryException;
use MyCLabs\Enum\Enum;

final class Country extends Enum
{
    const CODE_ABW = 'ABW';
    const CODE_AFG = 'AFG';
    const CODE_AGO = 'AGO';
    const CODE_AIA = 'AIA';
    const CODE_ALA = 'ALA';
    const CODE_ALB = 'ALB';
    const CODE_AND = 'AND';
    const CODE_ARE = 'ARE';
    const CODE_ARG = 'ARG';
    const CODE_ARM = 'ARM';
    const CODE_ASM = 'ASM';
    const CODE_ATA = 'ATA';
    const CODE_ATF = 'ATF';
    const CODE_ATG = 'ATG';
    const CODE_AUS = 'AUS';
    const CODE_AUT = 'AUT';
    const CODE_AZE = 'AZE';
    const CODE_BDI = 'BDI';
    const CODE_BEL = 'BEL';
    const CODE_BEN = 'BEN';
    const CODE_BES = 'BES';
    const CODE_BFA = 'BFA';
    const CODE_BGD = 'BGD';
    const CODE_BGR = 'BGR';
    const CODE_BHR = 'BHR';
    const CODE_BHS = 'BHS';
    const CODE_BIH = 'BIH';
    const CODE_BLM = 'BLM';
    const CODE_BLR = 'BLR';
    const CODE_BLZ = 'BLZ';
    const CODE_BMU = 'BMU';
    const CODE_BOL = 'BOL';
    const CODE_BRA = 'BRA';
    const CODE_BRB = 'BRB';
    const CODE_BRN = 'BRN';
    const CODE_BTN = 'BTN';
    const CODE_BVT = 'BVT';
    const CODE_BWA = 'BWA';
    const CODE_CAF = 'CAF';
    const CODE_CAN = 'CAN';
    const CODE_CCK = 'CCK';
    const CODE_CHE = 'CHE';
    const CODE_CHL = 'CHL';
    const CODE_CHN = 'CHN';
    const CODE_CIV = 'CIV';
    const CODE_CMR = 'CMR';
    const CODE_COD = 'COD';
    const CODE_COG = 'COG';
    const CODE_COK = 'COK';
    const CODE_COL = 'COL';
    const CODE_COM = 'COM';
    const CODE_CPV = 'CPV';
    const CODE_CRI = 'CRI';
    const CODE_CUB = 'CUB';
    const CODE_CUW = 'CUW';
    const CODE_CXR = 'CXR';
    const CODE_CYM = 'CYM';
    const CODE_CYP = 'CYP';
    const CODE_CZE = 'CZE';
    const CODE_DEU = 'DEU';
    const CODE_DJI = 'DJI';
    const CODE_DMA = 'DMA';
    const CODE_DNK = 'DNK';
    const CODE_DOM = 'DOM';
    const CODE_DZA = 'DZA';
    const CODE_ECU = 'ECU';
    const CODE_EGY = 'EGY';
    const CODE_ERI = 'ERI';
    const CODE_ESH = 'ESH';
    const CODE_ESP = 'ESP';
    const CODE_EST = 'EST';
    const CODE_ETH = 'ETH';
    const CODE_FIN = 'FIN';
    const CODE_FJI = 'FJI';
    const CODE_FLK = 'FLK';
    const CODE_FRA = 'FRA';
    const CODE_FRO = 'FRO';
    const CODE_FSM = 'FSM';
    const CODE_GAB = 'GAB';
    const CODE_GBR = 'GBR';
    const CODE_GEO = 'GEO';
    const CODE_GGY = 'GGY';
    const CODE_GHA = 'GHA';
    const CODE_GIB = 'GIB';
    const CODE_GIN = 'GIN';
    const CODE_GLP = 'GLP';
    const CODE_GMB = 'GMB';
    const CODE_GNB = 'GNB';
    const CODE_GNQ = 'GNQ';
    const CODE_GRC = 'GRC';
    const CODE_GRD = 'GRD';
    const CODE_GRL = 'GRL';
    const CODE_GTM = 'GTM';
    const CODE_GUF = 'GUF';
    const CODE_GUM = 'GUM';
    const CODE_GUY = 'GUY';
    const CODE_HKG = 'HKG';
    const CODE_HMD = 'HMD';
    const CODE_HND = 'HND';
    const CODE_HRV = 'HRV';
    const CODE_HTI = 'HTI';
    const CODE_HUN = 'HUN';
    const CODE_IDN = 'IDN';
    const CODE_IMN = 'IMN';
    const CODE_IND = 'IND';
    const CODE_IOT = 'IOT';
    const CODE_IRL = 'IRL';
    const CODE_IRN = 'IRN';
    const CODE_IRQ = 'IRQ';
    const CODE_ISL = 'ISL';
    const CODE_ISR = 'ISR';
    const CODE_ITA = 'ITA';
    const CODE_JAM = 'JAM';
    const CODE_JEY = 'JEY';
    const CODE_JOR = 'JOR';
    const CODE_JPN = 'JPN';
    const CODE_KAZ = 'KAZ';
    const CODE_KEN = 'KEN';
    const CODE_KGZ = 'KGZ';
    const CODE_KHM = 'KHM';
    const CODE_KIR = 'KIR';
    const CODE_KNA = 'KNA';
    const CODE_KOR = 'KOR';
    const CODE_KWT = 'KWT';
    const CODE_LAO = 'LAO';
    const CODE_LBN = 'LBN';
    const CODE_LBR = 'LBR';
    const CODE_LBY = 'LBY';
    const CODE_LCA = 'LCA';
    const CODE_LIE = 'LIE';
    const CODE_LKA = 'LKA';
    const CODE_LSO = 'LSO';
    const CODE_LTU = 'LTU';
    const CODE_LUX = 'LUX';
    const CODE_LVA = 'LVA';
    const CODE_MAC = 'MAC';
    const CODE_MAF = 'MAF';
    const CODE_MAR = 'MAR';
    const CODE_MCO = 'MCO';
    const CODE_MDA = 'MDA';
    const CODE_MDG = 'MDG';
    const CODE_MDV = 'MDV';
    const CODE_MEX = 'MEX';
    const CODE_MHL = 'MHL';
    const CODE_MKD = 'MKD';
    const CODE_MLI = 'MLI';
    const CODE_MLT = 'MLT';
    const CODE_MMR = 'MMR';
    const CODE_MNE = 'MNE';
    const CODE_MNG = 'MNG';
    const CODE_MNP = 'MNP';
    const CODE_MOZ = 'MOZ';
    const CODE_MRT = 'MRT';
    const CODE_MSR = 'MSR';
    const CODE_MTQ = 'MTQ';
    const CODE_MUS = 'MUS';
    const CODE_MWI = 'MWI';
    const CODE_MYS = 'MYS';
    const CODE_MYT = 'MYT';
    const CODE_NAM = 'NAM';
    const CODE_NCL = 'NCL';
    const CODE_NER = 'NER';
    const CODE_NFK = 'NFK';
    const CODE_NGA = 'NGA';
    const CODE_NIC = 'NIC';
    const CODE_NIU = 'NIU';
    const CODE_NLD = 'NLD';
    const CODE_NOR = 'NOR';
    const CODE_NPL = 'NPL';
    const CODE_NRU = 'NRU';
    const CODE_NZL = 'NZL';
    const CODE_OMN = 'OMN';
    const CODE_PAK = 'PAK';
    const CODE_PAN = 'PAN';
    const CODE_PCN = 'PCN';
    const CODE_PER = 'PER';
    const CODE_PHL = 'PHL';
    const CODE_PLW = 'PLW';
    const CODE_PNG = 'PNG';
    const CODE_POL = 'POL';
    const CODE_PRI = 'PRI';
    const CODE_PRK = 'PRK';
    const CODE_PRT = 'PRT';
    const CODE_PRY = 'PRY';
    const CODE_PSE = 'PSE';
    const CODE_PYF = 'PYF';
    const CODE_QAT = 'QAT';
    const CODE_REU = 'REU';
    const CODE_ROU = 'ROU';
    const CODE_RUS = 'RUS';
    const CODE_RWA = 'RWA';
    const CODE_SAU = 'SAU';
    const CODE_SDN = 'SDN';
    const CODE_SEN = 'SEN';
    const CODE_SGP = 'SGP';
    const CODE_SGS = 'SGS';
    const CODE_SHN = 'SHN';
    const CODE_SJM = 'SJM';
    const CODE_SLB = 'SLB';
    const CODE_SLE = 'SLE';
    const CODE_SLV = 'SLV';
    const CODE_SMR = 'SMR';
    const CODE_SOM = 'SOM';
    const CODE_SPM = 'SPM';
    const CODE_SRB = 'SRB';
    const CODE_SSD = 'SSD';
    const CODE_STP = 'STP';
    const CODE_SUR = 'SUR';
    const CODE_SVK = 'SVK';
    const CODE_SVN = 'SVN';
    const CODE_SWE = 'SWE';
    const CODE_SWZ = 'SWZ';
    const CODE_SXM = 'SXM';
    const CODE_SYC = 'SYC';
    const CODE_SYR = 'SYR';
    const CODE_TCA = 'TCA';
    const CODE_TCD = 'TCD';
    const CODE_TGO = 'TGO';
    const CODE_THA = 'THA';
    const CODE_TJK = 'TJK';
    const CODE_TKL = 'TKL';
    const CODE_TKM = 'TKM';
    const CODE_TLS = 'TLS';
    const CODE_TON = 'TON';
    const CODE_TTO = 'TTO';
    const CODE_TUN = 'TUN';
    const CODE_TUR = 'TUR';
    const CODE_TUV = 'TUV';
    const CODE_TWN = 'TWN';
    const CODE_TZA = 'TZA';
    const CODE_UGA = 'UGA';
    const CODE_UKR = 'UKR';
    const CODE_UMI = 'UMI';
    const CODE_URY = 'URY';
    const CODE_USA = 'USA';
    const CODE_UZB = 'UZB';
    const CODE_VAT = 'VAT';
    const CODE_VCT = 'VCT';
    const CODE_VEN = 'VEN';
    const CODE_VGB = 'VGB';
    const CODE_VIR = 'VIR';
    const CODE_VNM = 'VNM';
    const CODE_VUT = 'VUT';
    const CODE_WLF = 'WLF';
    const CODE_WSM = 'WSM';
    const CODE_YEM = 'YEM';
    const CODE_ZAF = 'ZAF';
    const CODE_ZMB = 'ZMB';
    const CODE_ZWE = 'ZWE';

    public function __construct($value)
    {
        if (is_string($value)) {
            $value = trim(filter_var($value, FILTER_UNSAFE_RAW));
        }

        parent::__construct($value);
    }

    /**
     * @throws CountryException
     */
    public static function isValid($value)
    {
        if (empty($value)) {
            throw CountryException::emptyValue();
        }

        if (!in_array($value, Country::toArray())) {
            throw CountryException::invalidValue();
        }
    }
}
